[package]
name = "build-master"
version = "0.1.0"
authors = ["bryal <96.bryal@gmail.com>"]

[dependencies]
nickel = "0.8"
libc = "0.2"
getopts = "0.2"
rustc-serialize = "0.3"
markdown = "0.1"
mustache = "0.7"